name: GPU passthrough

on:
  pull_request:
    paths:
      - '.github/workflows/gpu-passthrough-tests.yml'
      - '.github/workflows/testflinger/**'
  schedule:
    - cron: '38 6 */5 * *'
  workflow_dispatch:
    inputs:
      ubuntu-releases:
        description: Ubuntu releases to run the tests against. In JSON format, i.e. '["jammy", "noble"]'.
        type: choice
        default: '["noble"]'
        options:
          - '["jammy", "noble"]'
          - '["jammy"]'
          - '["noble"]'
      snap-track:
        description: Snap track to run the tests i.e. '["latest/edge", "6/candidate"]'.
        type: choice
        default: '["latest/edge"]'
        options:
          - '["latest/edge"]'
          - '["latest/candidate"]'
          - '["latest/stable"]'
          - '["6/edge"]'
          - '["6/candidate"]'
          - '["6/stable"]'
          - '["5.21/edge"]'
          - '["5.21/candidate"]'
          - '["5.21/stable"]'

jobs:
  uc-nvidia-cdi:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os:
          - core24-latest
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/uc-nvidia-cdi-job.yml \
            > $TESTFLINGER_DIR/uc-nvidia-cdi-job.temp
          mv $TESTFLINGER_DIR/uc-nvidia-cdi-job.temp $TESTFLINGER_DIR/uc-nvidia-cdi-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/uc-nvidia-cdi-job.yml

  nvidia-cdi:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/nvidia-cdi-job.yml \
            > $TESTFLINGER_DIR/nvidia-cdi-job.temp
          mv $TESTFLINGER_DIR/nvidia-cdi-job.temp $TESTFLINGER_DIR/nvidia-cdi-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-cdi-job.yml

  nvidia-legacy-runtime:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/nvidia-legacy-runtime-job.yml \
            > $TESTFLINGER_DIR/nvidia-legacy-runtime-job.temp
          mv $TESTFLINGER_DIR/nvidia-legacy-runtime-job.temp $TESTFLINGER_DIR/nvidia-legacy-runtime-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-legacy-runtime-job.yml
  amd-cdi:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-amd
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/amd-cdi-job.yaml \
            > $TESTFLINGER_DIR/amd-cdi-job.temp
          mv $TESTFLINGER_DIR/amd-cdi-job.temp $TESTFLINGER_DIR/amd-cdi-job.yaml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/amd-cdi-job.yaml
