name: NVIDIA GPU passthrough (containers)

on:
  pull_request:
    paths:
      - '.github/workflows/nvidia-test.yml'
      - '.github/workflows/testflinger/**'
  schedule:
    - cron: '38 6 */5 * *'
  workflow_dispatch:
    inputs:
      ubuntu-releases:
        description: Ubuntu releases to run the tests against. In JSON format, i.e. '["jammy", "noble"]'.
        type: choice
        default: '["noble"]'
        options:
          - '["jammy", "noble"]'
          - '["jammy"]'
          - '["noble"]'
      snap-track:
        description: Snap track to run the tests i.e. '["latest/edge", "5.0/candidate"]'.
        type: choice
        default: '["latest/edge"]'
        options:
          - '["latest/edge"]'
          - '["latest/candidate"]'
          - '["latest/stable"]'
          - '["6/edge"]'
          - '["6/candidate"]'
          - '["6/stable"]'
          - '["5.21/edge"]'
          - '["5.21/candidate"]'
          - '["5.0/edge"]'
          - '["5.0/candidate"]'
          - '["5.0/stable"]'
          - '["4.0/edge"]'
          - '["4.0/candidate"]'
          - '["4.0/stable"]'

jobs:
  uc24-cdi-test:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os:
          - core24-latest
        exclude:
          # skip tracks without CDI support
          - track: "4.0/candidate"
          - track: "4.0/edge"
          - track: "5.0/candidate"
          - track: "5.0/edge"
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/uc-nvidia-cdi-job.yml \
            > $TESTFLINGER_DIR/uc-nvidia-cdi-job.temp
          mv $TESTFLINGER_DIR/uc-nvidia-cdi-job.temp $TESTFLINGER_DIR/uc-nvidia-cdi-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/uc-nvidia-cdi-job.yml

  cdi-test:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
        exclude:
          # skip tracks without CDI support
          - track: "4.0/candidate"
          - track: "4.0/edge"
          - track: "5.0/candidate"
          - track: "5.0/edge"
          # skip track/os combinations that are too far appart
          - os: noble
            track: "4.0/candidate"
          - os: noble
            track: "4.0/edge"
          - os: noble
            track: "5.0/candidate"
          - os: noble
            track: "5.0/edge"
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/nvidia-cdi-job.yml \
            > $TESTFLINGER_DIR/nvidia-cdi-job.temp
          mv $TESTFLINGER_DIR/nvidia-cdi-job.temp $TESTFLINGER_DIR/nvidia-cdi-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-cdi-job.yml

  nvidia-runtime-test:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
        exclude:
          # skip track/os combinations that are too far appart
          - os: noble
            track: "4.0/candidate"
          - os: noble
            track: "4.0/edge"
          - os: noble
            track: "5.0/candidate"
          - os: noble
            track: "5.0/edge"
    env:
      TESTFLINGER_DIR: .github/workflows/testflinger
      SNAP_CHANNEL: ${{ matrix.track }}
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Create Testflinger job
        env:
          JOB_QUEUE: lxd-nvidia
          DISTRO: ${{ matrix.os }}
        run: |
          # Prepare job
          envsubst '$JOB_QUEUE $DISTRO $SNAP_CHANNEL' \
            < $TESTFLINGER_DIR/nvidia-legacy-runtime-job.yml \
            > $TESTFLINGER_DIR/nvidia-legacy-runtime-job.temp
          mv $TESTFLINGER_DIR/nvidia-legacy-runtime-job.temp $TESTFLINGER_DIR/nvidia-legacy-runtime-job.yml

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-legacy-runtime-job.yml
